### PR TITLE
Release 1.10.2

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
cc: @jeremyleung521 let me know (no rush!) when there are some tarballs on PyPI

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by jeremyleung521** [comment]
> cc: @jeremyleung521 let me know (no rush!) when there are some tarballs on PyPI

@mattwthompson 
Wheels and source tarball should be up!

https://pypi.org/project/mdtraj/#mdtraj-1.10.2.tar.gz

**Comment by jeremyleung521** [comment]
For some reason some of the builds are still installing numpy 1.XX, which is odd. 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1106606&view=logs&j=d93976e3-6ed1-588b-ebf8-e8a19c2becc4&t=90b382e2-e6d3-5178-8133-a486ee34063f&l=2246

Ah, [L40](https://github.com/conda-forge/mdtraj-feedstock/blob/main/recipe/meta.yaml#L40), which was proposed to be removed in #70, is might be forcing it to the lowest numpy version. That might conflict with numpy2 installs. since numpy1 compiled files don't work with numpy 2. [link](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice)

I wonder if the best practice is to pin `numpy` @ build time to `>2.0.0` here in the mdtraj source code to ensure compatibility instead https://github.com/mdtraj/mdtraj/blob/master/pyproject.toml#L6

**Comment by mattwthompson** [comment]
(Only have a moment to write this comment, sorry) I think the conda-forge maintainer docs have a section about this? On balance I'd prefer new builds use 2.x if I'm remembering correctly that it's backwards compatible to some new-ish 1.x

Or possibly an upstream only works on 1.x?

**Comment by jeremyleung521** [comment]
> (Only have a moment to write this comment, sorry) I think the conda-forge maintainer docs have a section about this? On balance I'd prefer new builds use 2.x if I'm remembering correctly that it's backwards compatible to some new-ish 1.x
> 
> Or possibly an upstream only works on 1.x?

Apparently we needed the `numpy2.yaml` file for the migration as well, in addition to the removal of L40. So I cherry-picked the commit over. We needed the migration to build for numpy2.
https://github.com/mattwthompson/mdtraj-feedstock/pull/1

Alternatively, we can merge this in, and then modify #70 to rebuild using 1.10.2. (or vice versa)

**Comment by marscher** [comment]
I think np-2.0 has some really clever way of being ABI compatible with 1.x
So we just need to make sure mdtraj is being build using np-2.0.

@jeremyleung521 the build log lines you've pointed out are showing the installation (testing) phase of the conda recipe. So it could be that another dependency of mdtraj is restraining to np-1.x

**Comment by mattwthompson** [comment]
> Alternatively, we can merge this in, and then modify https://github.com/conda-forge/mdtraj-feedstock/pull/70 to rebuild using 1.10.2. (or vice versa)

Normally I'd go for this but this release basically only exists for that migration, so let's give it a spin like this

**Comment by jeremyleung521** [comment]
> I think np-2.0 has some really clever way of being ABI compatible with 1.x
> So we just need to make sure mdtraj is being build using np-2.0.
> 
> @jeremyleung521 the build log lines you've pointed out are showing the installation (testing) phase of the conda recipe. So it could be that another dependency of mdtraj is restraining to np-1.x

If you scroll up, the host sections picked Numpy 1.XX (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1106606&view=logs&j=d93976e3-6ed1-588b-ebf8-e8a19c2becc4&t=90b382e2-e6d3-5178-8133-a486ee34063f&l=816) and the ci files names have Numpy 1.XX [on them](https://github.com/conda-forge/mdtraj-feedstock/pull/72/commits/bb9f2f4dcb789a1317e3d9e2c25fc2a3ea152bcf#diff-92cdfbff63d16524c6e15ed56f7f64ca0aff6fd57fa1c61792ec078bb667465c) . But in #70, that is not the case, which is why the numpy2.yaml migration file is needed to swap from building on numpy 1 to Numpy 2.

I've tested it locally and it would build on numpy 2 after #70's commit...

**Comment by marscher** [comment]
cant we let the migration bot do its job and then dissallow np-2.0 at runtime for the old version, then just merge this one here?

**Comment by mattwthompson** [comment]
There's a `numpy >=1.21,<3` in a `run:` secion of the most recent build logs. I don't think that's what we want (the lower bound should be 1.26?) and I don't know where it comes from

**Comment by mattwthompson** [comment]
> 
cant we let the migration bot do its job and then dissallow np-2.0 at runtime for the old version, then just merge this one here?

yeah, one option is to roll back 827c675970589f2926a07aa04dae48532895f451 and let the bot re-do the migration separately. I think the results will be about the same

**Comment by marscher** [comment]
the results, yes. But the road towards it may be less bumpy

**Comment by mattwthompson** [comment]
I'm fine with either path in general, but in this case I don't really think there's a value add from builds of the new version without the migration. The release had two changes, one being NumPy 2 and the other being the non-conda build dependencies: https://github.com/mdtraj/mdtraj/releases/tag/1.10.2

**Comment by jeremyleung521** [comment]
1.19/1.21 is picked depending on the python version because of something mentioned here: https://numpy.org/neps/nep-0053-c-abi-evolution.html#backwards-compatible-builds (v1.19 is the first one that supported python 3.9, for example), and the <3 is what [we pinned in the setup.py](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L301)

If we want to drop those support, we should actually pin it >=1.26.0 in the setup.py in the main repo.

**Comment by mattwthompson** [comment]
I don't really care, it's just a lower version than I expected which triggers my intuition that something else could be wrong

I'm fine with this as-is, if other packages in somebody's environment need 2.x or a newer 1.x that's up to other dependencies to define

**Comment by jeremyleung521** [comment]
Okay. #70 should be ready. Then after that is merged we can pull the changed from main into this PR, fix the conflicts, rerender, then merge this.

EDIT: Or alternatively we can just go ``@conda-forge-admin, please rerun bot`` on #73 . That'll save the headache for dealing with the conflicts

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
Cool - re-kicking CI to be safe, and then merging (could I get a "review" from either of you?) and moving on to #70

**Comment by jeremyleung521** [comment]
Sorry for flip flopping, but I think doing everything in this branch (via https://github.com/conda-forge/mdtraj-feedstock/commit/827c675970589f2926a07aa04dae48532895f451) is still the best way to go. That way we're not touching the good builds for 1.10.1.

If we do #70, we'll have a 1.10.1 "broken build", where if people want to revert/pull/install 1.10.1 in the future, they'll pull a build that is built on numpy2, "supports" numpy2 in the sense you can install it, but the code itself is not numpy2-compliant because it's not 1.10.2. That doesn't sound like good practice or right.

**Pull request closed without merging**
