### PR TITLE
Rebuild for linux aarch64

### PR DESCRIPTION
**Pull request by mlund**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I added `mdtraj` to the arch rebuild in the pinning-feedstock (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5454), and figure that a new build should be triggered.

### CODE REVIEW

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
Sorry, totally missed this

Does this differ from https://github.com/conda-forge/mdtraj-feedstock/pull/55?

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by mattwthompson** [comment]
Tag #69

**Comment by jeremyleung521** [comment]
Now #74. Bot had to reopen due to file conflicts.

**Pull request closed without merging**
