### PR TITLE
rerender with smithy 2.0.1 and try to reenable all builds

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
pandas is not yet available for numpy-1.12

**Comment by marscher** [comment]
* pandas for np112 has been merged yesterday.
* pytables not yet available for np112
* Appveyor on py27 failed in tng for not finding stdint.h

**Comment by marscher** [comment]
ping @mpharrigan: the builds for np112 of pytables and pandas are there. Can you please re-run CI?

**Comment by mpharrigan** [comment]
Thanks for investigating this. I've restarted the ci jobs

**Comment by marscher** [comment]
@mpharrigan The roundf error also occurs here. Since Python 2.7 is still contained in conda-forge's build matrix, I'll encourage to fix this. Unfortunately I have no clue, why this particular error pops up.

**Comment by marscher** [comment]
I'll open up a PR with this fix for mdtraj.

**Comment by mpharrigan** [comment]
Thanks so much @marscher . Just to be safe, I'm going to wait for travis-ci to run. I'll check back periodically, but if you notice it's finished, please ping me :)

**Comment by marscher** [comment]
press the button, please

**Comment by mpharrigan** [comment]
thanks!

**Comment by jakirkham** [comment]
Will need a new re-rendering to add NumPy 1.12 to Windows builds.

**Pull request merged**
