### PR TITLE
Skipping OSX builds

### PR DESCRIPTION
**Pull request by jeremyleung521**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Basically #51

### CODE REVIEW

**Comment by jeremyleung521** [comment]
Seems like all osx builds are failing... I switched off building for all the osx builds.

**Review by mattwthompson — APPROVED** [review]
Trusting the automation here a lot, but I think this should be good to merge?

Obviously we should look at the macOS failures - in this or the next release - but the tradeoff here seems clearly positive.

**Comment by jeremyleung521** [comment]
Had a quick look:

Something in these assignments (4 errors around line 1064,  4 errors around line 9651) are no longer valid on macos. 
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/tng/src/lib/tng_io.c#L1064

Anyhow, not immediately apparent what changed between the working runs in July and now, but probably require some digging here and in the source code.

And I agree it's probably ok to merge. the older macos builds will still be around for people to use.

**Comment by mattwthompson** [comment]
That makes total sense - I patched over that issue by just ignoring `.tng`-related tests in the main repo. I personally didn't know that trajectory format existed until it was causing failing tests here, so it might be worth dropping it if the fix is not straightforward.

Anyway, that's a separate issue altogether. Getting Linux (and Windows, I guess?) builds on Python 3.12 is a win.

**Comment by mattwthompson** [comment]
Thanks for the patch!

**Pull request merged**
