### PR TITLE
bump version 1.9.2

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
@mpharrigan this build is based upon the github src archive for 1.9.2, since we yet lack a pypi release.

**Comment by mpharrigan** [comment]
are we going to make a pypi release?

**Comment by mpharrigan** [comment]
appveyor failed for some reason. triggering a re-build

**Comment by marscher** [comment]
> are we going to make a pypi release?
>
Sure why not? In the release thread nobody responded, who has permissions
for pypi though.

**Comment by mpharrigan** [comment]
I can give you pypi permissions. What is your username there?

edit: found it from the pyemma page and it matches your github username

**Comment by marscher** [comment]
Done. I think we are good to go now

**Comment by mpharrigan** [comment]
nice!

**Comment by marscher** [comment]
pr #17 can be closed.

**Pull request merged**
