### PR TITLE
Constrain `cython =0.29`

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeremyleung521** [comment]
Probably failing because the version before cython 3 is [0.29.36](https://pypi.org/project/Cython/0.29.36/). A `=0.29` or `<3` should work.

**Comment by mattwthompson** [comment]
Oh, woah, it jumped from 0.29 to 3.0?

**Review by sroet — APPROVED** [review]
These changes LGTM, feel free to merge.

**Comment by sroet** [comment]
Hmm, I just now realize that I don't remember if pins were done with single or double equal signs. Do you mind doing a test-install tomorrow to make sure this recipe is correct @mattwthompson? Or are you certain of the syntax?

**Comment by mattwthompson** [comment]
I'm pretty confident the single `=` syntax is appropriate here - I don't think the builds would pass if there was a major problem. It's possible some builds pull down an older version than 0.29.36 or whatever is most recent, but until somebody reports an issue I'd prefer keeping that looser than a patch-level pin.

**Pull request merged**
