### PR TITLE
v1.9.7

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sroet** [comment]
Do you mind dropping the build number back to 0? (As the version is changing)

**Comment by mattwthompson** [comment]
Good catch - thanks!

**Comment by mattwthompson** [comment]
@conda-forge-admin please rerender

**Review by sroet — APPROVED** [review]
Looks good to me, feel free to merge

**Comment by mattwthompson** [comment]
Great - thanks for the review!

**Pull request merged**
