### PR TITLE
Sane numpy rerender

### PR DESCRIPTION
**Pull request by kain88-de**
1. update conda smithy render version

2. build against old numpy ABI [docs](https://conda-forge.org/docs/meta.html#building-against-numpy)

The last change results in a reduction of the build matrix and you don't have to publish a new package version when a new numpy version is released.

### CODE REVIEW

**Comment by kain88-de** [comment]
Btw a merge currently will fail due to a outdated anaconda token that this repository is still likely using

**Comment by kain88-de** [comment]
https://github.com/conda-forge/conda-forge.github.io/issues/426

**Comment by kain88-de** [comment]
@ocefpaf [appvevor](https://ci.appveyor.com/project/conda-forge/mdtraj-feedstock/build/1.0.31/job/u591y2yyosmh1t77) There is an error on py35 and x64 complaining about incompatible numpy/python versions. Is this related to the timeout problems that I see on the other tests that fail or is there a numpy package missing on the channel?

**Comment by mpharrigan** [comment]
Does this actually work? Has numpy kept their ABI the same since 1.8?

**Comment by kain88-de** [comment]
Yes. We are already using it for other packages. This is also the strategy to package widely usable wheel packages to distribute on PyPi.

**Pull request closed without merging**
