### PR TITLE
Rebuild package with new compilers

### LINKED ISSUE #1547: Python 3.10 release?
Background: PyEmma is a testing dependency for a package I maintain. We are trying to enable tests on python 3.10.

Currently when trying to run `conda install pyemma` in a python `3.10` environment, this fails with:

```
conda install pyemma
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                   

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyemma -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.10
```

reproducer (assuming you have conda-forge added as a channel in conda):
```
conda create -n test python
conda activate test
conda install pyemma
```

What would be required for PyEMMA to be build on python 3.10 (other than the conda-forge bots doing their magic)?

### PR DESCRIPTION
**Pull request by clonker**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Hi, I have a linker issue on PR conda-forge/pyemma-feedstock#41 and I think updating the images and compilers here might resolve it. Hence this PR :slightly_smiling_face: 

@sroet this would also resolve markovmodel/PyEMMA#1547 (took a while...)

### CODE REVIEW

**Comment by clonker** [comment]
@conda-forge-admin, please rerender

**Review by mattwthompson — APPROVED** [review]
Seems fine to me once builds finish. At first I was surprised to see the compiler version bump by 3 but I guess that's just how Clang does it. Can't get much simpler than bumping the build number and letting the automation spin!

@sroet feel free to merge this yourself, or @clonker ping me again and I'll hit the button

**Comment by clonker** [comment]
Thanks @mattwthompson ! Builds have passed.

**Comment by sroet** [comment]
LGTM, merging

**Pull request merged**
