### PR TITLE
Enable OSX builds

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
@mattwthompson i think this should fix the build issues you were seeing... seemed to be a 'this was previously a warning but now an error by default in the new clang' issue

**Review by mattwthompson — APPROVED** [review]
LGTM - should I upstream into the repo itself as well?

To be honest seeing a file named `basesetup.py` in the base of a repo scares me more than a little, so I haven't looked into it what's going on there

**Comment by SimonBoothroyd** [comment]
yup, I think it probably should be!

**Comment by mattwthompson** [comment]
Thanks for the patch!

**Comment by mattwthompson** [comment]
Tracking context: I'm pretty sure https://github.com/conda-forge/mdtraj-feedstock/pull/52 is where we turned off macOS/OS X builds altogether

**Pull request merged**
